[[pages]]
path="bot_page.py"
name="Copilot"
icon="ğŸ "

[[pages]]
path="pages/user_profile_form_page.py"
name="User Profile"
icon=":books:"

[[pages]]
path="pages/calendar_page.py"
name="Calendar"
icon=":calendar:"
